language: python
python:
  - "3.8"
  - "3.9"
install: 
  - pip install -r requirements.txt
script: 
  - python -m unittest discover -s tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ${PYPI_TOKEN}
  on:
    tags: true
    python: 3.9
  skip_existing: true
  verbose: true